// Guided tour and end-of-demo CTA — runs the real js/demoTour.js via the vm harness and drives
// it the way a visitor (or a keyboard-only visitor) would: clicking rendered buttons and
// pressing Escape, not calling internal step-index state directly.
const { test, describe } = require('node:test');
const assert = require('node:assert/strict');
const { loadDemoEnv } = require('./helpers/loadDemoEnv.js');

describe('guided demo tour', () => {
  test('starts on step 1 of 5 with the Executive Dashboard step', () => {
    const env = loadDemoEnv();
    env.dtStart();
    const html = env.document.getElementById('dt-card').innerHTML;
    assert.ok(html.includes('Step 1 of 5'));
    assert.ok(html.includes('Executive Dashboard'));
  });

  test('Next advances through all 5 documented steps in order, ending on Role-Based Access', () => {
    const env = loadDemoEnv();
    env.dtStart();
    const titles = ['Executive Dashboard', 'Role Switcher', 'Recruitment CRM', 'Attendance Tracking', 'Role-Based Access'];
    titles.forEach((title, i) => {
      const html = env.document.getElementById('dt-card').innerHTML;
      assert.ok(html.includes(title), `expected step ${i + 1} to show "${title}", got: ${html.slice(0, 80)}`);
      if (i < titles.length - 1) env.document.getElementById('dt-next-btn').onclick();
    });
  });

  test('the Role Switcher step highlights the real role-switcher control', () => {
    const env = loadDemoEnv();
    env.dtStart();
    env.document.getElementById('dt-next-btn').onclick(); // -> step 2, Role Switcher
    assert.ok(env.document.getElementById('demo-role-switcher').classList.contains('demo-tour-highlight'));
  });

  test('Back returns to the previous step without losing progress', () => {
    const env = loadDemoEnv();
    env.dtStart();
    env.document.getElementById('dt-next-btn').onclick();
    env.document.getElementById('dt-next-btn').onclick(); // now on step 3
    env.document.getElementById('dt-back-btn').onclick();
    assert.ok(env.document.getElementById('dt-card').innerHTML.includes('Step 2 of 5'));
  });

  test('the final step\'s action button performs the real role switch (no simulated/fake behavior)', () => {
    const env = loadDemoEnv();
    env.switchDemoRole('President');
    env.dtStart();
    for (let i = 0; i < 4; i++) env.document.getElementById('dt-next-btn').onclick();
    assert.ok(env.document.getElementById('dt-action-btn'), 'expected an action button on the last step');
    env.document.getElementById('dt-action-btn').onclick();
    assert.equal(env.CURRENT_USER.title, 'General Member');
    assert.equal(env.CURRENT_USER.role, 'viewer');
  });

  test('Escape dismisses the tour and the dismissal is remembered (does not reappear once closed)', () => {
    const env = loadDemoEnv();
    assert.equal(env.dtDismissedBefore(), false);
    env.dtStart();
    env.dtOnKeydown({ key: 'Escape' });
    assert.equal(env.dtDismissedBefore(), true);
    assert.equal(env.document.getElementById('dt-card'), null, 'tour card should be removed from the document on dismiss');
  });

  test('Skip tour also dismisses and remembers dismissal', () => {
    const env = loadDemoEnv();
    env.dtStart();
    env.document.getElementById('dt-skip-btn').onclick();
    assert.equal(env.dtDismissedBefore(), true);
    assert.equal(env.document.getElementById('dt-card'), null);
  });

  test('starting the tour twice does not stack a second card (real double-start guard)', () => {
    const env = loadDemoEnv();
    env.dtStart();
    env.document.getElementById('dt-next-btn').onclick(); // move off step 1
    env.dtStart(); // should no-op since a card already exists
    assert.ok(env.document.getElementById('dt-card').innerHTML.includes('Step 2 of 5'), 'a second dtStart() call reset progress, but it should have been a no-op');
  });

  test('"Take the tour" stays reachable from the demo banner regardless of prior dismissal', () => {
    const env = loadDemoEnv();
    env.localStorage.setItem('ato_demo_tour_dismissed', '1');
    assert.equal(env.dtDismissedBefore(), true);
    env.dtStart(); // the banner's onclick calls dtStart() directly, bypassing the dismissed-check
    assert.ok(env.document.getElementById('dt-card'), 'tour should still be manually startable after a prior dismissal');
  });
});

describe('end-of-demo CTA', () => {
  test('uses the marketing site\'s verified early-access and homepage routes, not guessed URLs', () => {
    const env = loadDemoEnv();
    env.switchDemoRole('President');
    env.dtCtaInit();
    // The CTA's two links are static markup in index.html (not generated by JS), verified once
    // here against the exact hrefs shipped in the page.
    const html = require('fs').readFileSync(require('path').resolve(__dirname, '..', 'index.html'), 'utf8');
    const ctaSection = html.slice(html.indexOf('id="demo-cta-card"'), html.indexOf('id="demo-cta-card"') + 900);
    assert.ok(ctaSection.includes('href="https://atoexec.com/intake"'), 'Get Early Access should link to the marketing site\'s real intake route');
    assert.ok(ctaSection.includes('href="https://atoexec.com"'), 'Return to ATOExec.com should link to the marketing site root');
  });

  test('dismissing the CTA persists and it stays hidden on the next render', () => {
    const env = loadDemoEnv();
    env.switchDemoRole('President');
    env.renderDash();
    assert.equal(env.document.getElementById('demo-cta-card').style.display, '');
    env.document.getElementById('demo-cta-dismiss').onclick();
    assert.equal(env.document.getElementById('demo-cta-card').style.display, 'none');
    assert.equal(env.dtCtaDismissedBefore(), true);
    // Simulate the next render (e.g. navigating back to the Dashboard) — must stay dismissed.
    env.renderDash();
    assert.equal(env.document.getElementById('demo-cta-card').style.display, 'none');
  });
});
